spring:
  profiles:
    active: production
server:
  port: 5000

# develop
---
spring:
  config:
    activate:
      on-profile: develop

# production
---
spring:
  config:
    activate:
      on-profile: production
